################################################################################
# InitConfiguration
################################################################################
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
---
################################################################################
# ClusterConfiguration
################################################################################
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration

# Version Kubernetes
kubernetesVersion: v1.32.5

# RÃ©seau Pods / Services
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
  dnsDomain: cluster.local
